module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
          "on-secondary-container": "#784d00",
          "inverse-surface": "#343027",
          "surface-container-low": "#fbf3e5",
          "on-primary": "#ffffff",
          "surface-container-high": "#efe7d9",
          "primary-fixed-dim": "#9cd2b6",
          "on-secondary-fixed-variant": "#643f00",
          "secondary-fixed-dim": "#f8bb6a",
          "error-container": "#ffdad6",
          "outline": "#717973",
          "tertiary-fixed-dim": "#c9c6c1",
          "primary-container": "#184d38",
          "tertiary-fixed": "#e5e2dd",
          "surface-container-lowest": "#ffffff",
          "tertiary": "#2e2e2b",
          "inverse-primary": "#9cd2b6",
          "primary-fixed": "#b8efd2",
          "on-tertiary-fixed": "#1c1c19",
          "on-primary-container": "#88bda2",
          "on-tertiary": "#ffffff",
          "secondary-container": "#fec16f",
          "background": "#fffbf7",
          "on-error": "#ffffff",
          "surface": "#F3EBDD",
          "outline-variant": "#c0c9c2",
          "surface-dim": "#e1d9cb",
          "surface-container": "#f5eddf",
          "on-primary-fixed-variant": "#1b503a",
          "secondary-fixed": "#ffddb5",
          "tertiary-container": "#454441",
          "surface-container-highest": "#e9e2d4",
          "on-tertiary-container": "#b3b1ac",
          "error": "#ba1a1a",
          "inverse-on-surface": "#f8f0e2",
          "on-tertiary-fixed-variant": "#474743",
          "secondary": "#825509",
          "on-surface-variant": "#414942",
          "on-background": "#1f1b13",
          "primary": "#326950",
          "on-error-container": "#410002",
          "on-secondary": "#ffffff",
          "on-surface": "#1f1b13",
      },
      fontFamily: {
        montserrat: ['"Montserrat Alternates"', 'sans-serif'],
        sora: ['Sora', 'sans-serif'],
        epilogue: ['Epilogue', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
